name: CI

on:
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validar fluxo de branches
        run: |
          if [[ "${{ github.base_ref }}" == feature/* ]]; then
            echo "ERRO: não é permitido abrir PR para uma branch feature/*."
            exit 1
          fi

          if [ "${{ github.base_ref }}" = "develop" ]; then
            if [[ "${{ github.head_ref }}" != feature/* ]]; then
              echo "ERRO: apenas branches feature/* podem abrir PR para develop."
              exit 1
            fi

            echo "Fluxo válido: feature/* -> develop"
          fi

          if [ "${{ github.base_ref }}" = "main" ]; then
            if [ "${{ github.head_ref }}" != "develop" ]; then
              echo "ERRO: apenas develop pode abrir PR para main."
              exit 1
            fi

            echo "Fluxo válido: develop -> main"
          fi